NUMERIC_FEATURES = ['Year of Record',
                    'Crime Level in the City of Employement',
                    'Work Experience in Current Job [years]',
                    'Age',
                    'Size of City',
                    'Wears Glasses',
                    'Body Height [cm]',
                    'Yearly Income in addition to Salary (e.g. Rental Income)',
                    ]

CATEGORICAL_FEATURE = ['Housing Situation',
                       'Satisfation with employer',
                       'Gender',
                       'Country',
                       'Profession',
                       'University Degree',
                       'Hair Color',
                       ]

NA_VALUES = {'Year of Record': ['nan'],
             'Housing Situation': [0, 'nA'],
             'Crime Level in the City of Employement': [],
             'Work Experience in Current Job [years]': ['#NUM!'],
             'Satisfation with employer': ['nan'],
             'Gender': ['nan', 'unknown', 0, 'f'],
             'Age': [],
             'Country': [],
             'Size of City': [],
             'Profession': [],
             'University Degree': ['nan', 0, 'No'],
             'Wears Glasses': [],
             'Hair Color': ['Unknown', 0, 'nan'],
             'Body Height [cm]': [],
             'Yearly Income in addition to Salary (e.g. Rental Income)': [],
             }

FEATURES = ['Year of Record',
            'Housing Situation',
            'Crime Level in the City of Employement',
            'Work Experience in Current Job [years]',
            'Satisfation with employer',
            'Gender',
            'Age',
            'Country',
            'Size of City',
            'Profession',
            'University Degree',
            'Wears Glasses',
            'Hair Color',
            'Body Height [cm]',
            'Yearly Income in addition to Salary (e.g. Rental Income)',
            ]

CONVERTERS = {'Yearly Income in addition to Salary (e.g. Rental Income)': lambda x: float(x.split()[0])}
